name = "kapacitor.data"
stateful = true
serviceAlias = "kapacitor"
image = "kapacitor:1.3-alpine"

[scale]
  containers = 1
  ram = "> 50 Mi < 200 Mi"
  cpu = "> 10% < 20%"

[env]
  KAPACITOR_INFLUXDB_0_URLS_0 = "http://influxdb:8086"

[ports]
  http = "9092"

[mounts]
  kapacitor-data = "/var/lib/kapacitor"

[storage]
  kapacitor-data = "10Gi:exclusive"
