name = "chronograf.data"
stateful = true
serviceAlias = "chrono"
subdomain = "chrono"
image = "quay.io/influxdb/chronograf:1.3.5.0"

[scale]
  containers = 1
  ram = "> 50 Mi < 200 Mi"
  cpu = "> 10% < 20%"

[env]
  INFLUXDB_URL = "http://influxdb:8086"
  KAPACITOR_URL = "http://kapacitor:9092"

[ports]
  http = "8888"

[mounts]
  chronograf-data = "/var/lib/chronograf"

[storage]
  chronograf-data = "2Gi:exclusive"
